version: 2

project_name: kubectl-hpa-status

before:
  hooks:
    - go mod tidy

builds:
  - id: kubectl-hpa-status
    main: .
    binary: kubectl-hpa-status
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mattsu2020/kubectl-hpa-status/cmd.version={{ .Tag }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - LICENSE

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
